# logging
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) [%X{traceId}-%X{spanId}] %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

# actuator
management:
  health:
    rabbit:
      enabled: true
    binders:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
        - "*"

  tracing:
    enabled: true
    propagation: 
      type: b3
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      connect-timeout: 2s
      read-timeout: 5s
      endpoint: http://localhost:9411/api/v2/spans

# spring
spring:
  application:
    name: @project.name@

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    address-shuffle-mode: RANDOM
    addresses: localhost:5673,localhost:5674,localhost:5675