POST http://localhost:8080/post HTTP/1.1
Content-Type: application/json

{
    "message": "test",
    "details": [
        {
            "detail_message": "detail message"
        }
    ]
}

### exception test
POST http://localhost:8080/post HTTP/1.1
Content-Type: application/json

{
    "type": "exception",
    "message": "test",
    "details": [
        {
            "detail_message": "detail message"
        }
    ]
}

### conditionを再現
POST http://localhost:8080/routing/hoge HTTP/1.1
Content-Type: application/json

{
    "message": "hogehoge",
    "details": [
        {
            "detail_message": "detail message"
        }
    ]
}

### 
POST http://localhost:8080/routing/fuga HTTP/1.1
Content-Type: application/json

{
    "message": "fugafuga",
    "details": [
        {
            "detail_message": "detail message"
        }
    ]
}

### 
POST http://localhost:8080/routing/piyo HTTP/1.1
Content-Type: application/json

{
    "message": "piyopiyo",
    "details": [
        {
            "detail_message": "detail message"
        }
    ]
}