POST http://localhost:8080/post HTTP/1.1
Content-Type: application/json

{
    "message": "test",
    "details": [
        {
            "detail_message": "detail message"
        }
    ]
}

### exception test
POST http://localhost:8080/post HTTP/1.1
Content-Type: application/json

{
    "type": "exception",
    "message": "test",
    "details": [
        {
            "detail_message": "detail message"
        }
    ]
}